-------CRIANDO TABELA DE USUARIOS DO SISTEMA--------
CREATE TABLE usuarios(
ID_USUARIO    BIGSERIAL PRIMARY KEY,
NM_USUARIO    VARCHAR(256),
DT_NASCIMENTO DATE,
TP_SEXO       VARCHAR(1),
CD_USUARIO_CADASTRO VARCHAR(256),
DT_CADASTRO   TIMESTAMP,
CD_USU_ULT_ALT VARCHAR(256),
DT_ULT_ALT	  TIMESTAMP
)

-------CRIANDO TABELA DE SENHA DOS USUARIOS DO SISTEMA--------

CREATE TABLE usu_senhas(
ID_SENHA BIGSERIAL PRIMARY KEY,
ID_USUARIO BIGINT,
DS_SENHA VARCHAR(256),
CD_USUARIO_CADASTRO VARCHAR(256),
DT_CADASTRO   TIMESTAMP,
CD_USU_ULT_ALT VARCHAR(256),
DT_ULT_ALT	  TIMESTAMP,
FOREIGN KEY (ID_USUARIO) REFERENCES usuarios(ID_USUARIO)

)


----------------------------------------------------
INSERT INTO usuarios(NM_USUARIO, 
					 DT_NASCIMENTO, 
					 TP_SEXO, 
					 CD_USUARIO_CADASTRO, 
					 DT_CADASTRO, 
					 CD_USU_ULT_ALT, 
					 DT_ULT_ALT)
VALUES(
'leonardo.gomes',
'18/02/1999',
'M',
'MANAGER',
CURRENT_TIMESTAMP,
NULL,
NULL

)

INSERT INTO usu_senhas(
ID_USUARIO,
DS_SENHA,
CD_USUARIO_CADASTRO,
DT_CADASTRO,
CD_USU_ULT_ALT,
DT_ULT_ALT
)
VALUES(
1,
'Leo@100718',
'MANAGER',
CURRENT_TIMESTAMP,
NULL,
NULL

)




					 
					 